export const CREATE_CART_REQUEST = "CREATE_CART_REQUEST";
export const CREATE_CART_SUCCESS = "CREATE_CART_SUCCESS";
export const CREATE_CART_FAILED = "CREATE_CART_FAILED";

export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILED = "GET_CART_FAILED";

export const GET_CART_SUMMARY_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUMMARY_SUCCESS = "GET_CART_SUMMARY_SUCCESS";
export const GET_CART_SUMMARY_FAILED = "GET_CART_SUMMARY_FAILED";

export const ADD_CART_ITEM_REQUEST = "ADD_CART_ITEM_REQUEST";
export const ADD_CART_ITEM_SUCCESS = "ADD_CART_ITEM_SUCCESS";
export const ADD_CART_ITEM_FAILED = "ADD_CART_ITEM_FAILED";

export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST";
export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS";
export const UPDATE_CART_ITEM_FAILED = "UPDATE_CART_ITEM_FAILED";

export const DELETE_CART_ITEM_REQUEST = "DELETE_CART_ITEM_REQUEST";
export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS";
export const DELETE_CART_ITEM_FAILED = "DELETE_CART_ITEM_FAILED";

export const CART_SUMMARY_TOGGLE_TRUE = "CART_SUMMARY_TOGGLE_TRUE";
export const CART_SUMMARY_TOGGLE_FALSE = "CART_SUMMARY_TOGGLE_FALSE";

export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const DELETE_SHIPPING_ADDRESS = "DELETE_SHIPPING_ADDRESS";

export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
export const DELETE_PAYMENT_METHOD = "DELETE_PAYMENT_METHOD";
