export const SSALCOMMERZ_REQUEST = "SSALCOMMERZ_REQUEST";
export const SSALCOMMERZ_SUCCESS = "SSALCOMMERZ_SUCCESS";
export const SSALCOMMERZ_FAILED = "SSALCOMMERZ_FAILED";

export const SAVE_CART_AS_ORDER_REQUEST = "SAVE_CART_AS_ORDER_REQUEST";
export const SAVE_CART_AS_ORDER_SUCCESS = "SAVE_CART_AS_ORDER_SUCCESS";
export const SAVE_CART_AS_ORDER_FAILED = "SAVE_CART_AS_ORDER_FAILED";

export const GET_ORDER_ITEMS_REQUEST = "GET_ORDER_ITEMS_REQUEST";
export const GET_ORDER_ITEMS_SUCCESS = "GET_ORDER_ITEMS_SUCCESS";
export const GET_ORDER_ITEMS_FAILED = "GET_ORDER_ITEMS_FAILED";
