export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILED = "USER_REGISTRATION_FAILED";
export const USER_REGISTRATION_LOGIN = "USER_REGISTRATION_LOGIN";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAILED = "USER_DETAILS_FAILED";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_DETAILS_UPDATE_REQUEST = "USER_DETAILS_UPDATE_REQUEST";
export const USER_DETAILS_UPDATE_SUCCESS = "USER_DETAILS_UPDATE_SUCCESS";
export const USER_DETAILS_UPDATE_FAILED = "USER_DETAILS_UPDATE_FAILED";
export const USER_DETAILS_UPDATE_RESET = "USER_DETAILS_UPDATE_RESET";
